### ISSUE TITLE
STT0046: upload the new dataset in hugging face.

### ISSUE THREAD

**Issue by gangagyatso4364** [OpenPecha/stt-combine-datasets#4]
### Description

we need to update dataset repo in hugging face with the new dataset we have accumulated.
[training and validation dataset repo](https://huggingface.co/datasets/openpecha/tibetan_asr_data)
[benchmark dataset repo](https://huggingface.co/datasets/openpecha/tibetan-voice-benchmark)

### Completion Criteria
hugging face repo of benchmark and tibetan asr data with updated dataset.

### Subtask
- [x] clone the repos of benchmark and tibetan asr.
- [x] download the new benchmark and training data from aws.
- [x] update the data in repos.
- [x] update the meta data of the repos.

**Comment by kaldan007** [comment]
@gangagyatso4364 kindly point the code which includes the new dept data in benchmark.

**Comment by gangagyatso4364** [comment]
added meta to benchmark data.
